//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Card 
    {

        public Card()
        {
            this.Contacts = new HashSet<Contact>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public long BranchId { get; set; }
        public long SynCode { get; set; }
        public int StatusTypeId { get; set; }
    
        public virtual ICollection<Contact> Contacts { get; set; }
        public virtual StatusType StatusType { get; set; }
        public IEnumerator<object> GetEnumerator()
        {
            throw new NotImplementedException();
        }
    }
}
